project:
  type: site
  output-dir: _site

site:
  title: "Quarto"
  repo-url: https://github.com/quarto-dev/quarto-web
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
    contents:
      - section: "Getting Started"
        contents:
          - text: "Welcome"
            href: index.md
          - docs/getting-started/installation.md
          - docs/getting-started/quarto-basics.md
          - docs/getting-started/quarto-projects.md
      - section: "Computations"
        contents:
          - docs/computations/executing-code.md
          - docs/computations/using-jupyter-lab.md
          - docs/computations/using-rstudio.md
      - section: "Authoring"
        contents:
          - docs/authoring/document-options.Rmd
          - docs/authoring/markdown-basics.md
          - docs/authoring/footnotes-and-citations.md
          - docs/authoring/figures-and-layout.md
          - docs/authoring/cross-references.md
          - docs/authoring/callouts.md
          - docs/authoring/pandoc-filters.md
      - section: "Output Formats"
        contents:
          - section: "HTML"
            contents:
              - docs/output-formats/html-basics.Rmd
              - docs/output-formats/html-bootstrap.Rmd
              - docs/output-formats/html-themes.md
          - section: "PDF"
            contents:
              - docs/output-formats/pdf-basics.md
              - docs/output-formats/pdf-engine.md
          - docs/output-formats/ms-word.md
          - docs/output-formats/hugo.md
          - docs/output-formats/more-formats.md
      - section: "Websites"
        contents:
          - docs/websites/website-basics.md
          - docs/websites/website-navigation.md
          - docs/websites/publishing-websites.md
      - section: "Books"
        contents:
          - docs/books/book-basics.md
          - docs/books/book-authoring.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
filters:
  - filters/include-files.lua




