project:
  type: site
  output-dir: _site

site:
  title: "Quarto"
  image: "quarto.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web
  repo-actions: [edit, issue]
  page-navigation: true
  
  navbar:
    logo: quarto.png
    title: false
    search: true
    background: light
    type: light
    collapse-below: lg
    sidebar-menus: true
    
    right:
      - sidebar:get-started
      - sidebar:using
      - sidebar:formats
      - sidebar:projects
      - href: docs/gallery/index.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
    
  sidebar:
    - id: get-started
      title: "Get Started"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - section: "Get Started"
          contents:
            - text: "Welcome"
              href: index.qmd
            - docs/getting-started/installation.qmd
            - docs/getting-started/quarto-basics.qmd
            - docs/getting-started/running-code.qmd
        - section: "Code Editors"
          contents:
            - docs/tools/jupyter-lab.qmd
            - docs/tools/rstudio.qmd
            - docs/tools/vscode.qmd
            - docs/tools/text-editors.qmd
        - section: "Visual Editor"
          contents:
            - text: Editor Basics
              href: docs/visual-editor/index.qmd 
            - docs/visual-editor/technical.qmd
            - docs/visual-editor/content.qmd
            - docs/visual-editor/options.qmd
            - docs/visual-editor/markdown.qmd
          
    - id: using
      title: "Using"
      contents:
        - section: "Authoring"
          contents:
            - docs/authoring/markdown-basics.qmd
            - docs/authoring/footnotes-and-citations.qmd
            - docs/authoring/figures-and-layout.qmd
            - docs/authoring/cross-references.qmd
            - docs/authoring/callouts.qmd
            - docs/authoring/shortcodes-and-filters.qmd
        - section: "Computations"
          contents:
            - docs/computations/running-code.qmd
            - docs/computations/execution-options.qmd
            - docs/computations/parameters.qmd
        - section: "Interactive Docs"
          contents:
            - text: "Overview"
              href: docs/interactive/index.qmd
            - section: docs/interactive/js/index.qmd
              contents:
                - text: "Introduction"
                  href: docs/interactive/js/
                - docs/interactive/js/libraries.qmd
                - docs/interactive/js/data-sources.qmd
                - docs/interactive/js/ojs-cells.qmd
                - docs/interactive/js/shiny.qmd
                - docs/interactive/js/code-reuse.qmd
                - section: "Examples"
                  contents:
                    - docs/interactive/js/examples/penguins.qmd
                    - docs/interactive/js/examples/sunburst.qmd
                    - docs/interactive/js/examples/arquero.qmd
                    - docs/interactive/js/examples/population.qmd
                    - docs/interactive/js/examples/noaa-co2.qmd
                    - docs/interactive/js/examples/github.qmd
                    - text: "Shiny"
                      href: https://jjallaire.shinyapps.io/kmeans-shiny-ojs/
                    - docs/interactive/js/examples/layout.qmd
            - section: docs/interactive/shiny/index.qmd
              contents:
                - text: "Introduction"
                  href: docs/interactive/shiny/index.qmd
                - docs/interactive/shiny/running.qmd
                - docs/interactive/shiny/execution.qmd
                - docs/interactive/shiny/resources.qmd
            - section: "Widgets"
              contents:
                - docs/interactive/widgets/jupyter.qmd
                - docs/interactive/widgets/htmlwidgets.qmd
            - docs/interactive/layout.qmd
              
    - id: formats
      title: "Formats"
      contents:
        - section: "HTML"
          contents:
            - docs/output-formats/html-basics.qmd
            - docs/output-formats/html-code.qmd
            - docs/output-formats/html-themes.qmd
            - docs/output-formats/html-publishing.qmd
        - section: "PDF"
          contents:
            - docs/output-formats/pdf-basics.qmd
            - docs/output-formats/pdf-engine.qmd
        - section: "MS Word"
          contents:
            - docs/output-formats/ms-word.qmd
            - docs/output-formats/ms-word-templates.qmd
        - section: "Markdown"
          contents:
            - docs/output-formats/gfm.qmd
            - docs/output-formats/hugo.qmd
        - section: "Other"
          contents:
            - docs/output-formats/presentations.qmd
            - docs/output-formats/more-formats.qmd
            
    - id: projects
      title: "Projects"
      contents:
        - section: "Using Projects"
          contents:
            - docs/projects/quarto-projects.qmd
            - docs/projects/code-execution.qmd
            - docs/projects/virtual-environments.qmd
        - section: "Websites"
          contents:
            - docs/websites/website-basics.qmd
            - docs/websites/website-navigation.qmd
            - docs/websites/website-tools.qmd
            - docs/websites/publishing-websites.qmd
        - section: "Books"
          contents:
            - docs/books/book-basics.qmd
            - docs/books/book-authoring.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/include-files.lua



