project:
  title: "Quarto"
  type: website
  output-dir: docs

navbar:
  left:
    - text: "Home"
      href: index.md
    - text: "Learn More"
      href: figures-and-layout.md
  
sidebar:
  logo: "/images/quarto.png"
  style: "anchored"
  items:
    - text: "Getting Started"
      items:
        - href: index.md
          text: "Introduction"
        - href: basic-usage.md
        - href: html-themes.md
    - text: "Learning More"
      items:
        - href: figures-and-layout.md
        - href: cross-references.md
        - href: pdfs-and-latex.md
        - href: quarto-projects.md
        - href: quarto-extensions.md
    - text: "Using with knitr"
      items:
        - href: rendering-rmds.md
        - href: https://yihui.org/knitr/
          text: "knitr Options"
    - text: "Using with Jupyter"
      items:
        - href: jupyter-markdown.md
        - href: jupyter-options.md
        - href: exporting-notebooks.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

