project:
  type: site
  output-dir: docs

site:
  title: "Quarto"
  repo-url: https://github.com/quarto-dev/quarto-cli
  repo-actions: [edit]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/quarto-dev/quarto-cli
          - text: Report a Bug
            href:  https://github.com/quarto-dev/quarto-cli/issues/new
    contents:
      - section: "Getting Started"
        contents:
          - href: index.md
          - href: getting-started/basic-usage.md
          
      - section: "Computations"
        contents:
          - href: executing-code.md
          - href: using-jupyter-lab.md
          - href: using-rstudio.md
      - section: "Markdown"
        contents:
          - href: formatting.md
          - href: equations.md
          - href: figures-and-layout.md
          - href: footnotes-and-citations.md
          - href: cross-references.md
          - href: callouts.md
      - section: "Output Formats"
        contents:
          - section: "HTML"
            contents:
              - html-basics.Rmd
              - html-bootstrap.Rmd
              - html-themes.md
          - section: "PDF"
            contents:
              - href: pdf-basics.md
              - href: pdfs-and-latex.md
          - href: ms-word.md
          - href: presentations.md
          - href: epub.md
          - href: more-formats.md
      - section: "Projects"
        contents:
          - href: quarto-projects.md
          - section: "Websites"
            contents:
              - website-basics.md
              - website-navigation.md
          - section: "Books"
            contents:
              - book-basics.md
              - book-authoring.md


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



