project:
  type: site
  output-dir: docs

site:
  title: "Quarto"
  repo-url: https://github.com/quarto-dev/quarto-cli
  repo-actions: [edit]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/quarto-dev/quarto-cli
          - text: Report a Bug
            href:  https://github.com/quarto-dev/quarto-cli/issues/new
    contents:
      - section: "Getting Started"
        contents:
          - href: index.md
          - href: getting-started/basic-usage.md
          
      - section: "Computations"
        contents:
          - executing-code.md
          - using-jupyter-lab.md
          - using-rstudio.md
      - section: "Markdown"
        contents:
          - formatting.md
          - equations.md
          - figures-and-layout.md
          - footnotes-and-citations.md
          - cross-references.md
          - callouts.md
      - section: "Output Formats"
        contents:
          - section: "HTML"
            contents:
              - html-basics.Rmd
              - html-bootstrap.Rmd
              - html-themes.md
          - section: "PDF"
            contents:
              - pdf-basics.md
              - pdfs-and-latex.md
          - ms-word.md
          - presentations.md
          - epub.md
          - hugo.md
          - more-formats.md
      - section: "Websites"
        contents:
          - quarto-projects.md
          - websites/website-basics.md
          - websites/website-navigation.md
          - websites/publishing-websites.md
      - section: "Books"
        contents:
          - book-basics.md
          - book-authoring.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



