project:
  title: "quarto-docs"
  type: website
  output-dir: _site

navbar:
  type: dark
  background: primary
  left:
    - href: index.md
      text: Home
    - href: about.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "On this page"

