project:
  type: site
  output-dir: _site
  
execute:
  freeze: true

site:
  title: "Quarto"
  image: "quarto.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    logo: quarto.png
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
    contents:
      - section: "Getting Started"
        contents:
          - text: "Welcome"
            href: index.md
          - docs/getting-started/installation.md
          - docs/getting-started/quarto-basics.md
          - docs/getting-started/quarto-projects.md
      - section: "Computations"
        contents:
          - docs/computations/running-code.md
          - docs/computations/execution-options.md
          - docs/computations/using-jupyter-lab.md
          - docs/computations/using-rstudio.md
          - docs/computations/parameters.md
      - section: "Authoring"
        contents:
          - docs/authoring/markdown-basics.md
          - docs/authoring/footnotes-and-citations.md
          - docs/authoring/figures-and-layout.md
          - docs/authoring/cross-references.md
          - docs/authoring/callouts.md
          - docs/authoring/shortcodes-and-filters.md
      - section: "Output Formats"
        contents:
          - section: "HTML"
            contents:
              - docs/output-formats/html-basics.Rmd
              - docs/output-formats/html-code.Rmd
              - docs/output-formats/html-themes.md
              - docs/output-formats/html-publishing.md
          - section: "PDF"
            contents:
              - docs/output-formats/pdf-basics.md
              - docs/output-formats/pdf-engine.md
          - docs/output-formats/ms-word.md
          - section: "Markdown"
            contents:
              - docs/output-formats/gfm.md
              - docs/output-formats/hugo.md
          - docs/output-formats/presentations.md
          - docs/output-formats/more-formats.md
      - section: "Websites"
        contents:
          - docs/websites/website-basics.md
          - docs/websites/website-navigation.md
          - docs/websites/website-tools.md
          - docs/websites/publishing-websites.md
      - section: "Books"
        contents:
          - docs/books/book-basics.md
          - docs/books/book-authoring.md

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]

    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    
filters:
  - filters/include-files.lua




