project:
  type: site
  output-dir: docs

site:
  title: "Quarto"
  repo-url: https://github.com/quarto-dev/quarto-cli
  repo-actions: [edit]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/quarto-dev/quarto-cli
          - text: Report a Bug
            href:  https://github.com/quarto-dev/quarto-cli/issues/new
    contents:
      - section: "Getting Started"
        contents:
          - href: index.md
          - href: basic-usage.md
          - href: computations.md
          - href: authoring-tools.md
      - section: "Learning More"
        contents:
          - href: callouts.md
          - href: figures-and-layout.md
          - href: cross-references.md
          - href: pdfs-and-latex.md
          - href: quarto-projects.md
      - section: "HTML"
        contents:
          - html-basics.Rmd
          - html-bootstrap.Rmd
          - html-themes.md
          - website-basics.md
          - website-navigation.md
      - section: "Books"
        contents:
          - book-basics.md
          - book-authoring.md


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



