project:
  type: site
  output-dir: docs

site:
  title: "Quarto"
  sidebar:
    logo: images/quarto.png
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - href: index.md
          - href: basic-usage.md
          - href: html-themes.md
      - section: "Learning More"
        contents:
          - href: figures-and-layout.md
          - href: cross-references.md
          - href: pdfs-and-latex.md
          - href: quarto-projects.md
          - href: quarto-extensions.md
      - section: "Using with knitr"
        contents:
          - href: rendering-rmds.md
          - href: https://yihui.org/knitr/
            text: "knitr Options"
      - section: "Using with Jupyter"
        contents:
          - href: jupyter-markdown.md
          - href: jupyter-options.md
          - href: exporting-notebooks.md


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



