project:
  type: site
  output-dir: _site

site:
  title: "Quarto"
  repo-url: https://github.com/quarto-dev/quarto-cli
  repo-actions: [edit]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/quarto-dev/quarto-cli
          - text: Report a Bug
            href:  https://github.com/quarto-dev/quarto-cli/issues/new
    contents:
      - section: "Getting Started"
        contents:
          - href: index.md
          - href: docs/getting-started/installation.md
          - href: docs/getting-started/quarto-basics.md
          - href: docs/getting-started/quarto-projects.md
          
      - section: "Computations"
        contents:
          - docs/computations/executing-code.md
          - docs/computations/using-jupyter-lab.md
          - docs/computations/using-rstudio.md
      - section: "Markdown"
        contents:
          - docs/markdown/formatting.md
          - docs/markdown/equations.md
          - docs/markdown/figures-and-layout.md
          - docs/markdown/footnotes-and-citations.md
          - docs/markdown/cross-references.md
          - docs/markdown/callouts.md
      - section: "Output Formats"
        contents:
          - section: "HTML"
            contents:
              - docs/output-formats/html-basics.Rmd
              - docs/output-formats/html-bootstrap.Rmd
              - docs/output-formats/html-themes.md
          - section: "PDF"
            contents:
              - docs/output-formats/pdf-basics.md
              - docs/output-formats/pdfs-and-latex.md
          - docs/output-formats/ms-word.md
          - docs/output-formats/presentations.md
          - docs/output-formats/epub.md
          - docs/output-formats/hugo.md
          - docs/output-formats/more-formats.md
      - section: "Websites"
        contents:
          - docs/websites/website-basics.md
          - docs/websites/website-navigation.md
          - docs/websites/publishing-websites.md
      - section: "Books"
        contents:
          - docs/books/book-basics.md
          - docs/books/book-authoring.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



