project:
  type: site
  output-dir: _site
  
site:
  title: "Quarto"
  image: "quarto.png"
  google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web
  repo-actions: [edit, issue]
  page-navigation: true
  
  navbar:
    logo: quarto.png
    search: true
    background: light
    type: light
    collapse-below: md
    right:
      - sidebar:get-started
      - sidebar:using
      - sidebar:formats
      - sidebar:projects
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
    
  sidebar:
    - id: get-started
      title: "Get Started"
      style: "docked"
      background: light
      collapse-level: 2
      align: left
      contents:
        - section: "Get Started"
          contents:
          - text: "Welcome"
            href: index.qmd
          - docs/getting-started/installation.qmd
          - docs/getting-started/quarto-basics.qmd
          - docs/getting-started/running-code.qmd
          - docs/getting-started/quarto-projects.qmd
          
    - id: using
      title: "Using"
      contents:
        - section: "Authoring"
          contents:
            - docs/authoring/markdown-basics.qmd
            - docs/authoring/footnotes-and-citations.qmd
            - docs/authoring/figures-and-layout.qmd
            - docs/authoring/cross-references.qmd
            - docs/authoring/callouts.qmd
            - docs/authoring/shortcodes-and-filters.qmd
        - section: "Computations"
          contents:
            - docs/computations/running-code.qmd
            - docs/computations/execution-options.qmd
            - docs/computations/using-jupyter-lab.qmd
            - docs/computations/using-rstudio.qmd
            - docs/computations/parameters.qmd
            
    - id: formats
      title: "Formats"
      contents:
        - section: "HTML"
          contents:
            - docs/output-formats/html-basics.qmd
            - docs/output-formats/html-code.qmd
            - docs/output-formats/html-themes.qmd
            - docs/output-formats/html-publishing.qmd
        - section: "PDF"
          contents:
            - docs/output-formats/pdf-basics.qmd
            - docs/output-formats/pdf-engine.qmd
        - section: "Markdown"
          contents:
            - docs/output-formats/gfm.qmd
            - docs/output-formats/hugo.qmd
        - section: "Other"
          contents:
            - docs/output-formats/ms-word.qmd
            - docs/output-formats/presentations.qmd
            - docs/output-formats/more-formats.qmd
            
    - id: projects
      title: "Projects"
      contents:
        - section: "Using Projects"
          contents:
            - docs/projects/quarto-projects.qmd
            - docs/projects/code-execution.qmd
            - docs/projects/virtual-environments.qmd
        - section: "Websites"
          contents:
            - docs/websites/website-basics.qmd
            - docs/websites/website-navigation.qmd
            - docs/websites/website-tools.qmd
            - docs/websites/publishing-websites.qmd
        - section: "Books"
          contents:
            - docs/books/book-basics.qmd
            - docs/books/book-authoring.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]

    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    
filters:
  - filters/include-files.lua




