[[plugins]]
  package = "@quarto/netlify-plugin-quarto"

  package = "netlify-plugin-github-dispatch"
    [plugins.inputs]
      owner = "quarto-dev" 
      repo = "quarto-web" # use the target repo name
      workflow = ".github/workflows/upload-index.yml"
