name: PR commands trigger

on:
  issue_comment:
    types: [created]

jobs:
  deploy-preview-external-pr:
    # Allow only members and owners to trigger the deploy preview using the /deploy-preview command
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/deploy-preview') }}
    uses: ./.github/workflows/preview.yml
    with:
      deploy-preview-comment: true
    secrets: inherit