on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      deploy-preview-comment:
        required: true
        type: boolean
  issue_comment:
    types: [created]

name: Deploy Preview

jobs:
  check-external-pr:
    # Be helpful with reviewer and remind them to trigger a deploy preview if the PR is from a fork.
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.head.repo.fork == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for opening a PR to contribute ! Reminder to reviewer: Start a comment with `/deploy-preview` to trigger a deploy of preview to Netlify. Preview link will then be poster in the comment. Please note that the preview will be deleted once the PR is closed or merged'
            })

  trigger-preview-external-pr:
    # Allow only members and owners to trigger the deploy preview using the /deploy-preview command
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/deploy-preview') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering deploy preview for PR #${{ github.event.issue.number }}"

  build-deploy-preview:
    needs: trigger-preview-external-pr
    # Deploy a preview only if the PR is not from a fork, or explicitly requested by manually by API or PR comment.
    if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork != true) || needs.trigger-preview-external-pr.result == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Render 
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: html

      - name: Deploy Preview to Netlify as preview
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v2
        env:
          NETLIFY_SITE_ID: 2a3da659-672b-4e5b-8785-e10ebf79a962
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          publish-dir: './_site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          alias: deploy-preview-${{ github.event.number }}
          # these all default to 'true'
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        timeout-minutes: 1