# Regenerates the download json
name: Update Downloads
on:
  workflow_dispatch:
  schedule:
    - cron:  "*/15 * * * *"
jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Regenerate Download Json
        uses: ./.github/workflows/actions/release-info
        with:
          owner: 'quarto-dev'
          repo: 'quarto-cli'
          out-path: 'docs/download/_download.json'
          github-token: ${{ github.token }}
      - name: Copy Download Json to Site
        run: |
          cp docs/download/_download.json _site/docs/download/_download.json
      - name: Commit Changes
        uses: actions-x/commit@v2
        with:
          email: runner@quarto.org
          name: Github Action Runner
          files: docs/download/_download.json _site/docs/download/_download.json
    
        
        
          
