# Regenerates the download json
name: Update Downloads
on:
  workflow_dispatch:
jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Regenerate Download Json
        uses: ./.github/workflows/actions/release-info
        with:
          owner: 'quarto-dev'
          repo: 'quarto-cli'
          out-path: 'downloads.json'
          github-token: ${{ github.token }}
        
        
          
