# Regenerates the download json
name: Update Downloads
on:
  workflow_dispatch:
jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Regenerate Download Json
        uses: ./.github/workflows/actions/release-info
        with:
          owner: 'quarto-dev'
          repo: 'quarto-cli'
          out-path: '_download-data.html'
          out-template: |
            <script type="application/javascript">
            window['quarto-dl-data'] = $$DOWNLOAD_JSON$$;
            </script>
          github-token: ${{ github.token }}
      - name: push
        uses: actions-x/commit@v2
        with:
          email: runner@quarto.org
          name: Github Action Runner
          files: '_download-data.html'
    
        
        
          
