# Uploads index to our Algolia Index
name: Upload Index
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    # only trigger on branches, not on tags
    branches: [main]
jobs:
  upload-index:
    runs-on: ubuntu
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6        
      - name: Install Algolia API Dependencies
        run: |
          gem install algolia
      - name: Upload Index
        run: ruby upload.rb

